# Generated by Django 4.0.4 on 2022-05-09 22:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to=core.models.upload_to, verbose_name='Image')),
                ('nv', models.DecimalField(decimal_places=3, max_digits=3)),
                ('mel', models.DecimalField(decimal_places=3, max_digits=3)),
                ('bkl', models.DecimalField(decimal_places=3, max_digits=3)),
                ('bcc', models.DecimalField(decimal_places=3, max_digits=3)),
                ('akiec', models.DecimalField(decimal_places=3, max_digits=3)),
                ('vasc', models.DecimalField(decimal_places=3, max_digits=3)),
                ('df', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
