# Generated by Django 4.0.4 on 2022-05-09 23:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_skincancer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skincancer',
            name='image',
            field=models.ImageField(upload_to=core.models.upload_to, verbose_name='Image'),
        ),
    ]
