# Generated by Django 4.0.4 on 2022-05-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_skincancer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skincancer',
            name='akiec',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skincancer',
            name='bcc',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skincancer',
            name='bkl',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skincancer',
            name='df',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skincancer',
            name='mel',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skincancer',
            name='nv',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='skincancer',
            name='vasc',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
